/*
 * parser.h
 *
 *  Created on: 2017年10月26日
 *      Author: Jeremy.Hsiao
 */

#ifndef SRC_APP_USB_CDC_STR_PACK_PARSER_PARSER_H_
#define SRC_APP_USB_CDC_STR_PACK_PARSER_PARSER_H_

typedef enum {
	ENUM_PARSING_STATE_WAIT_SYNC_BYTE = 0,				 // Also initial state
	ENUM_PARSING_STATE_WAIT_CARRIER_WIDTH_HIGH,
    ENUM_PARSING_STATE_WAIT_CARRIER_WIDTH_LOW,
    ENUM_PARSING_STATE_WAIT_PULSE_WIDTH_WAIT_1ST_INPUT,
    ENUM_PARSING_STATE_WAIT_PULSE_WIDTH_WAIT_WORD_LOW,
    ENUM_PARSING_STATE_WAIT_PULSE_WIDTH_WAIT_LONG_2ND,
    ENUM_PARSING_STATE_WAIT_PULSE_WIDTH_WAIT_LONG_3RD,
    ENUM_PARSING_STATE_WAIT_PULSE_WIDTH_WAIT_LONG_4TH,
    ENUM_PARSING_STATE_UNKNOWN_STATE,
    ENUM_PARSING_STATE_MAX
} ENUM_PARSING_STATE;

extern ENUM_PARSING_STATE ProcessInputChar_and_ReturnNextState(ENUM_PARSING_STATE current_state, uint8_t input_byte);

#endif /* SRC_APP_USB_CDC_STR_PACK_PARSER_PARSER_H_ */
