#ifndef _IO_H
#define _IO_H

#include "LPC11U37_401.h"

#define IR_LED_OUT_HIGH         Set_LED(1);
#define IR_LED_OUT_LOW          Set_LED(0);
#define IR_LED_OUT_TOGGLE       Toggle_LED();

#define IR_RX_GPIO_PORT_NUM			TIMER32_B0_CAP0_PORT
#define IR_RX_GPIO_BIT_NUM			TIMER32_B0_CAP0_PIN

#define IR_TX_GPIO_PORT_NUM			TIMER32_B1_MAT0_PORT
#define IR_TX_GPIO_BIT_NUM			TIMER32_B1_MAT0_PIN

#define IRDA_RX_GPIO_PORT_NUM		1
#define IRDA_RX_GPIO_BIT_NUM		15

#define CEC_GPIO_PORT_NUM			TIMER16_B0_CAP0_PORT
#define CEC_GPIO_BIT_NUM			TIMER16_B0_CAP0_PINT

#define HSYNC_GPIO_PORT_NUM			TIMER16_B1_CAP0_PORT
#define HSYNC_GPIO_BIT_NUM			TIMER16_B1_CAP0_PINT

#define UART_TX_GPIO_PORT_NUM		0
#define UART_TX_GPIO_BIT_NUM		19

#define UART_RX_GPIO_PORT_NUM		0
#define UART_RX_GPIO_BIT_NUM		18

#define TEST_OUT1_GPIO_PORT_NUM		0
#define TEST_OUT1_GPIO_BIT_NUM		22

#define ADC_KEY0_GPIO_PORT_NUM      0
#define ADC_KEY0_GPIO_BIT_NUM       11

#define SSP0_SCK_GPIO_PORT_NUM      2
#define SSP0_SCK_GPIO_BIT_NUM       11

#define SSP0_SSEL_GPIO_PORT_NUM     3
#define SSP0_SSEL_GPIO_BIT_NUM      0

#define SSP0_MISO_GPIO_PORT_NUM     0
#define SSP0_MISO_GPIO_BIT_NUM      8

#define SSP0_MOSI_GPIO_PORT_NUM     0
#define SSP0_MOSI_GPIO_BIT_NUM      9


#define MY_BUTTONS_BUTTON1_GPIO_PORT_NUM		0
#define MY_BUTTONS_BUTTON1_GPIO_BIT_NUM			23
#define MY_JOYSTICK_UP_GPIO_PORT_NUM			1
#define MY_JOYSTICK_UP_GPIO_BIT_NUM				22
#define MY_JOYSTICK_DOWN_GPIO_PORT_NUM			1
#define MY_JOYSTICK_DOWN_GPIO_BIT_NUM			23
#define MY_JOYSTICK_LEFT_GPIO_PORT_NUM			1
#define MY_JOYSTICK_LEFT_GPIO_BIT_NUM			24
#define MY_JOYSTICK_RIGHT_GPIO_PORT_NUM			1
#define MY_JOYSTICK_RIGHT_GPIO_BIT_NUM			25
#define MY_JOYSTICK_PRESS_GPIO_PORT_NUM			1
#define MY_JOYSTICK_PRESS_GPIO_BIT_NUM			26


#endif //_IO_H
